import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-HK">
      <body
        className={`antialiased h-screen w-screen flex flex-col items-center`}
      >
        <main className={"border-2 border-teal-300 h-full w-full xl:w-[1024px]"}>
          <header className={"h-[50px] w-full bg-mainGreen hidden xl:flex"}>
            aa
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
